print ('Cat 1:')
catName1 = input()
print ('Cat 2:')
catName2 = input()
print ('Cat 3:')
catName3 = input()
print ('Cat 4:')
catName4 = input()
print ('Cat 1:')
catName5 = input()
print ('Cat 1:')
catName6 = input()

print ('Here are you cats: ' +catName1 + catName2 + catName3+ catName4 + catName5 + catName6)
