print("I will now count my chickens: ")

print ("Hens: " , float(25 + 30 / 6))
print ("Roosters: ", float(100 - 25 * 3 % 4))
print("Now i will count my eggs: ")
print(3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6)
print("Is it true that 3 + 2 < 5 = 7?")
print (3 + 2 < 5 - 7)
print("What is 3 + 2? ", float(3 + 2))
print("What is 5 - 7? ", float(5 - 7 ))
print("Oh that's why its false")
print("How about some more eggs")
print("Is it greater?", 5 > -2 )
print("Is it greater or equal?", 5 >= -2)
print("Is it less or equal?", 5 <= -2)